language: minimal

services: docker

addons:
    apt:
        packages:
            - docker-compose


env:
    global:
        # hyphen in project names are stripped away in Travis's CI old docker-compose version
        - COMPOSE_PROJECT_NAME=jatsingester
        - IMAGE_REVISION=$TRAVIS_COMMIT
        - IMAGE_TAG=$TRAVIS_COMMIT

install:
    - docker-compose version
    - travis_retry docker-compose build

script:
    - make tests
    - .travis/smoke-test.sh

after_success:
    - .scripts/travis/push-image.sh jats-ingester

deploy:
    provider: script
    script: .scripts/travis/downstream.sh environments "Update jats-ingester to $TRAVIS_COMMIT"
    on:
        branch: master

if: |
    branch = master OR \
    branch =~ /^(?:[0-9]|[1-9][0-9]*)\.(?:[0-9]|[1-9][0-9]*)$/ OR \
    tag IS present OR \
    type = pull_request
